### ISSUE TITLE
Error file while trying to use this software for Heart of Irons IV

### ISSUE THREAD

**Issue by ZeroKrazy** [BigBoiCJ/SteamAutoCracker#10]
The text file named: error.txt
inside it said this

Traceback (most recent call last):
  File "steam_auto_cracker.py", line 463, in <module>
  File "sac_lib\get_file_version.py", line 4, in GetFileVersion
pywintypes.error: (1813, 'GetFileVersionInfo:GetFileVersionInfoSize', 'The specified resource type cannot be found in the image file.')

Hope this helps

**Comment by BigBoiCJ** [comment]
Thanks, I'm looking into it.

**Comment by BigBoiCJ** [comment]
Works fine for me. My guess is that you downloaded an already-cracked release, and the cracked steam_api64.dll file didn't contain version info.

**Comment by ZeroKrazy** [comment]
Hmm, that's strange. I'll go ahead and retry and let you know of any update. Thanks for the reply.
(p.s: I got heart of iron 3-4 days ago from the steam store during the Christmas sale if that helps).
Gonna have a go at it again.

**Comment by ZeroKrazy** [comment]
Found out after some digging, my stupid brain forgot that I have 2 steam folders for 2 drives and Heart of iron was in a different drive and my location was set for the wrong drive lol.
//fixed

**Comment by BigBoiCJ** [comment]
Good to hear you found out what the problem was! If you have any question or problem, feel free to open a new issue ;)
