### ISSUE TITLE
Help, I Can't Use It

### ISSUE THREAD

**Issue by SuperPcAgency** [BigBoiCJ/SteamAutoCracker#13]
Traceback (most recent call last):
  File "steam_auto_cracker.py", line 390, in <module>
  File "steam_auto_cracker.py", line 115, in FindGameDirectory
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:/Users/ventu/Music/T6 By AvatarDZ (NF)/'
[error.log](https://github.com/BigBoiCJ/SteamAutoCracker/files/11002098/error.log)

**Comment by BigBoiCJ** [comment]
The error seems self explanatory, your configured `Pirated Games location` doesn't not exist

You can modify it by editing the config.ini file, be sure of what you're doing though, correct format is something like `D:/Games/Pirated/` (which you seem to have respected)

Else, you can delete the config file and restart the program, and it'll ask you to configure it again.

**Comment by GDH4ne** [comment]
I may be dumb but I followed your advice, however it gives me always the same error:
<img width="677" alt="image" src="https://user-images.githubusercontent.com/69966423/232144434-37f4e6fe-b573-42b2-911a-68d2b0e24518.png">
(yea i'm trying to crack clickteam fusion)

**Comment by BigBoiCJ** [comment]
Sorry for the misunderstanding, when it's asking for the folder name here, it's asking for the folder name for `Clickteam Fusion`, inside your CrackedGames folder.

Are you trying to crack a game that you didn't download? SAC won't download games for you, you first have to download the games files (ex: on CS.RIN.RU) then run SAC to remove the anti-piracy measures.

**Comment by BigBoiCJ** [comment]
Closed due to inactivity. Reopen if you need to :)
