### ISSUE TITLE
Does not work for Doom (2016)

### ISSUE THREAD

**Issue by ExplodingFistz** [BigBoiCJ/SteamAutoCracker#15]
I own the Doom (2016) game on Steam and I wanted to play this game without opening Steam launcher (it only has Steam DRM). So I used this tool to crack the game and it said afterwards the crack process was successful. Everything is good up until I try to load into the game. I do not mean by startup, but during the time when the game has to load up to main menu. Whenever it loads to 100% the game crashes immediately.

I suspect the crash might be happening because it is trying to connect to the multiplayer servers for the game. Not sure how to fix it though.

**Comment by BigBoiCJ** [comment]
I don't think SAC can crack Doom, I think it uses custom DRMs

**Comment by BigBoiCJ** [comment]
Closed due to inactivity. Reopen if you need to :)
