### ISSUE TITLE
DLC cracking failed

### ISSUE THREAD

**Issue by BadCat999** [BigBoiCJ/SteamAutoCracker#17]
After the recent update of RunningWithRifles, DLC cracking has not been successful, as it was previously successful.
AppID:270150
It seems successful, but it doesn't actually work.
Unable to select DLC map in the game.

**Comment by BadCat999** [comment]
[steam]
; Application ID (http://store.steampowered.com/app/%appid%/)
appid = 270150
; Current game language.
; Uncomment this option to turn it on.
; Default is "english".
;language = german
; Enable/disable automatic DLC unlock. Default option is set to "false".
; Keep in mind that this option  WON'T work properly if the "[dlc]" section is NOT empty
unlockall = false
; Original Valve's steam_api.dll.
; Default is "steam_api_o.dll".
orgapi = steam_api_o.dll
; Original Valve's steam_api64.dll.
; Default is "steam_api64_o.dll".
orgapi64 = steam_api64_o.dll
; Enable/disable extra protection bypasser.
; Default is "false".
extraprotection = false
; The game will think that you're offline (supported by some games).
; Default is "false".
forceoffline = false
; Some games are checking for the low violence presence.
; Default is "false".
;lowviolence = true
; Purchase timestamp for the DLC (http://www.onlineconversion.com/unix_time.htm).
; Default is "0" (1970/01/01).
;purchasetimestamp = 0

[steam_misc]
; Disables the internal SteamUser interface handler.
; Does have an effect on the games that are using the license check for the DLC/application.
; Default is "false".
disableuserinterface = false

[dlc]
; DLC handling.
; Format: <dlc_id> = <dlc_description>
; e.g. : 247295 = Saints Row IV - GAT V Pack
; If the DLC is not specified in this section
; then it won't be unlocked
1962410 = RUNNING WITH RIFLES: Veteran Pack
1484480 = RUNNING WITH RIFLES: EDELWEISS Soundtrack
1210750 = RUNNING WITH RIFLES: EDELWEISS
616850 = RUNNING WITH RIFLES: PACIFIC

**Comment by BigBoiCJ** [comment]
Maybe the DLC requires some files with it that are not in the base game. You can find those on cs.rin.ru

**Comment by BigBoiCJ** [comment]
any update on that?

**Comment by BigBoiCJ** [comment]
Closed due to inactivity, open again if needed
