### ISSUE TITLE
Mac support?

### ISSUE THREAD

**Issue by JonnycatMeow** [BigBoiCJ/SteamAutoCracker#18]
i was just wondering if there is gonna be mac support and i have a mac i can test it

**Comment by BigBoiCJ** [comment]
Probably not, sorry. This program uses Windows dependent things, and cracks games with DLLs. I think DLL files are windows only.

**Comment by BigBoiCJ** [comment]
I guess if you find steam emus for mac, then that could be done.
Unfortunately I don't have a mac and I'm not really interested in supporting it. If any other OS support is added, it'll probably be for Linux.
