### ISSUE TITLE
Battle Brothers, and CK2 not getting their DLC's cracked.

### ISSUE THREAD

**Issue by Agnestorm** [BigBoiCJ/SteamAutoCracker#19]
Any idea as to why when I use the GUI to crack these games -- it appears to break the game and not allow me to launch it anymore?
When I double click the shortcuts it effectively just loads for a moment and then does nothing and stops running.
Any fixes?

**Comment by BigBoiCJ** [comment]
Do you have the game on Steam? If so, you should probably download the DLC files first.

**Comment by Agnestorm** [comment]
> Do you have the game on Steam? If so, you should probably download the DLC files first.

Yes, I have both games on steam -- I also have a bought DLC for one of the games (Battle Brothers)
So I NEED to download the DLC files from per-se -- CS.RIN.RU and then use Steam Auto Crack?

**Comment by BigBoiCJ** [comment]
Yes. Or you can crack first, then download the DLC files. The order shouldn't matter.

**Comment by Agnestorm** [comment]
Thanks man, appreciate it greatly. It works now.

**Comment by Agnestorm** [comment]
> Quick reminder: not all games have separate DLC files, but for those that do, you must download them ;)

Yeah, I just realized that after cracking a separate game and it worked without downloading the DLC files.

**Comment by jaanaling** [comment]
Good afternoon! When trying to launch Battle Brothers, nothing happens, although the dlc is downloaded. What could be the problem?

; Battle Brothers
[steam]
appid = 365360
unlockall = false
orgapi = steam_api_o.dll
orgapi64 = steam_api64_o.dll
extraprotection = false
forceoffline = false

[steam_misc]
disableuserinterface = false

[dlc]
365382 = Battle Brothers - Fangshire Helm
732460 = Battle Brothers - Lindwurm
961930 = Battle Brothers - Beasts & Exploration
1067690 = Battle Brothers - Warriors of the North
1361280 = Battle Brothers - Blazing Deserts
1910050 = Battle Brothers - Of Flesh and Faith

**Comment by BigBoiCJ** [comment]
@jaanaling hi! Sorry for the late answer. Seems like you're using the CreamAPI (DLC) crack instead of a full game crack. Do you have the game (bought) on Steam? If not, switch to a proper game crack.
