### ISSUE TITLE
it dont work, barotruama dont work😭

### ISSUE THREAD

**Issue by AlhaFUN** [BigBoiCJ/SteamAutoCracker#22]
Traceback (most recent call last):
  File "steam_auto_cracker.py", line 390, in <module>
  File "steam_auto_cracker.py", line 115, in FindGameDirectory
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '"C:\\Users\\Privacy\\Downloads\\Barotrauma.v1.0.20.1"'

**Comment by BigBoiCJ** [comment]
This is likely due to a bad configuration of the program.

Go to `config.ini`, `[Locations]` and make sure paths are formated in this way:

`C:/Users/Privacy/Downloads/`

Use normal slashes `/`, finish with a slash, and don't specify an folder name.
Due to your folder not having a name that can be auto-detected, it might ask you to specify its name. Just enter `Barotrauma.v1.0.20.1` when asked.

**Comment by AlhaFUN** [comment]
k lemme try

**Comment by AlhaFUN** [comment]
new error😟

Traceback (most recent call last):
  File "steam_auto_cracker.py", line 477, in <module>
  File "sac_lib\get_file_version.py", line 4, in GetFileVersion
pywintypes.error: (1813, 'GetFileVersionInfo:GetFileVersionInfoSize', 'The specified resource type cannot be found in the image file.')

**Comment by BigBoiCJ** [comment]
Seems like your game already has a cracked steam_api(64).dll

**Comment by AlhaFUN** [comment]
wat

**Comment by AlhaFUN** [comment]
it still dosent work tho?

**Comment by AlhaFUN** [comment]
what do i do now

**Comment by AlhaFUN** [comment]
do i delete it and then it does it?

**Comment by BigBoiCJ** [comment]
It might have a more advanced DRM that SAC isn't able to automatically handle then, you should check CS.RIN.RU, sorry. That sometimes happen.

> do i delete it and then it does it?

No, it's likely SAC can't crack it.

**Comment by AlhaFUN** [comment]
hol up i got a idea

**Comment by AlhaFUN** [comment]
nvm, i got perm banned from reddit💀

**Comment by balogune** [comment]
Hello I'm new to cs.rin.ru . I downloaded pro evolution soccer 2017 the game has anti tamper drm. Will this work for it and also for cod games files from steam

**Comment by BigBoiCJ** [comment]
> Hello I'm new to cs.rin.ru . I downloaded pro evolution soccer 2017 the game has anti tamper drm. Will this work for it and also for cod games files from steam

@balogune SAC won't work with any custom DRMs. For AAA games and for those which use custom DRMs, I recommend getting the game on cs.rin.ru instead, through someone that knows what they're doing :)
Or you know, repacks are also good :)

https://rentry.org/pgames - reddit.com/r/PiratedGames contains great resources

SAC is made for those who need to crack small/medium games while having the clean steam files, or for removing the basic Steam DRM from your own games. It isn't an all in one solution to crack most games on Steam, but only to crack most **small** games on Steam :)
