### ISSUE TITLE
I don't understand

### ISSUE THREAD

**Issue by Sauroyn** [BigBoiCJ/SteamAutoCracker#23]
Hi,
I just want to crack a game like steep.
But for running the activator, i need to already have the game???
I yes, how can i download the game for free...
Sauroyn

**Comment by BigBoiCJ** [comment]
https://github.com/BigBoiCJ/SteamAutoCracker#notes-about-dlcs

You can get clean Steam files for games (and sometimes DLCs) in the [Steam Content Sharing section from cs.rin.ru](https://cs.rin.ru/forum/viewforum.php?f=22)
