### ISSUE TITLE
Steam Api service

### ISSUE THREAD

**Issue by donotprikel231** [BigBoiCJ/SteamAutoCracker#26]
I tried this on a game mod and it wont let me play the mod unless i have the original game installed but it checks with the steam api but it keeps saying i donot own the game which i do so will it work to trick the mod into letting me play it with the original game file. I HAD TO REPOST THIS BECAUSE GITHUB DOES NOT HAVE A CONFIRMATION TO CLOSE THE ISHUE ON ACSEDENT.

**Comment by BigBoiCJ** [comment]
You can reopen issues on github

**Comment by BigBoiCJ** [comment]
What's the mod in question? I've never tested those, only games.

**Comment by donotprikel231** [comment]
> What's the mod in question? I've never tested those, only games.

Its the LEGO Five nights at freddys 1 from gamejolt. It requiers the steam api to verify if the original fnaf game was bought on steam but i have the game but it keeps saying the game is not bought and i canot play the lego fnaf.

**Comment by donotprikel231** [comment]
Well i ment to say its not a mod it just checks with steam api to make shur the original game was purchased.

**Comment by BigBoiCJ** [comment]
I can't find the game. Maybe it could work by entering FNAF 1's appid in SAC? Try `319510`

**Comment by donotprikel231** [comment]
> I can't find the game. Maybe it could work by entering FNAF 1's appid in SAC? Try `319510`
> 
> But yea that's a thing I don't really know about.

The game was taken down after a dmca by lego. Heres a link to the archived version  https://archive.org/details/FNAFLEGO

**Comment by BigBoiCJ** [comment]
The mod probably uses another method that is unsupported by SAC to check if you have the game. Can't fix, sorry :-/

Using Goldberg's cracks might be the solution but it'll require more technical knowledge

**Comment by donotprikel231** [comment]
> 

Im a software hacker myself and ive looked through a hex editor to try to bypass the api checking screen and strait to the start menu. But thanks

**Comment by BigBoiCJ** [comment]
Great, if you know how to do that that's even better :) - hope you'll succeed or did succeed
