### ISSUE TITLE
Starting Problem

### ISSUE THREAD

**Issue by AnTh0ny138** [BigBoiCJ/SteamAutoCracker#27]
When i open the .exe cmd opens and closes by itself instantly so i just used python when i use it i get this error could you help me with this ?
![Screenshot 2023-07-28 113925](https://github.com/BigBoiCJ/SteamAutoCracker/assets/140804621/e8c36df3-e4fc-4131-8243-632ac1b07e1b)

**Comment by BigBoiCJ** [comment]
Your Python installation seems a bit out of date, but you should be good by running `py -m pip install requests` (replace `py` by the command you use to start python from cmd)

When the .exe instantly closes, is there anything that is sent to error.log? That will allow me to fix the issue :)

**Comment by AnTh0ny138** [comment]
No nothing no error log only in the python way but in the .exe i double click it it opens for like 1 second and closes by itself.

**Comment by AnTh0ny138** [comment]
and i updated the python using your command and then what the cmd said to me "C:\Users\*******\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip" but still same error does it have like required version ?

**Comment by AnTh0ny138** [comment]
> Your Python installation seems a bit out of date, but you should be good by running `py -m pip install requests` (replace `py` by the command you use to start python from cmd)
> 
> When the .exe instantly closes, is there anything that is sent to error.log? That will allow me to fix the issue :)

No nothing no error log only in the python way but in the .exe i double click it it opens for like 1 second and closes by itself.

**Comment by AnTh0ny138** [comment]
and i updated the python using your command and then what the cmd said to me
"C:\Users\ ******* \AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip"
but when i turned it on again error but looks like different error 
![Screenshot 2023-07-29 231040](https://github.com/BigBoiCJ/SteamAutoCracker/assets/140804621/58ff01fb-ec74-46fe-9466-1589eb957ec8)

**Comment by BigBoiCJ** [comment]
Please check #16

`py -m pip install pywin32` might do the trick

**Comment by AnTh0ny138** [comment]
IT WORKS thanks for help if i will find some kind of bug i wont hesitate and report it to you :)
