### ISSUE TITLE
İt doesnt work

### ISSUE THREAD

**Issue by alfabe78h** [BigBoiCJ/SteamAutoCracker#28]
Hello i was trying to crack a game then it crashed and it gave me this error Traceback (most recent call last):
  File "steam_auto_cracker.py", line 500, in <module>
  File "configparser.py", line 1257, in __getitem__
KeyError: 'EmuConfig'

**Comment by alfabe78h** [comment]
Found it accidentally deleted one of the files

**Comment by BigBoiCJ** [comment]
Thanks for updating this issue, it could help other users that got the same problem :)
