### ISSUE TITLE
Steam API DLL

### ISSUE THREAD

**Issue by AnTh0ny138** [BigBoiCJ/SteamAutoCracker#29]
Finished cracking the game!
[ ! ] No Steam API DLL was found in the game!
Press enter to exit

uhh help i don't exactly know how to crack games this is my first so what can i do to make it find the Steam API DLL ?

**Comment by BigBoiCJ** [comment]
What game is it? Maybe it just doesn't have a steam api DLL.

You might also have selected the wrong game folder.

**Comment by AnTh0ny138** [comment]
i tried to crack one of the games that i then buyed i wanted to support the creator so i rather choose to buy it :) srr for the another issue if i will find something i will say

**Comment by AnTh0ny138** [comment]
i then decided that i buy the game i wanted to support the creator :)
if i will find some error while cracking some kind of game i will report it to you

**Comment by AnTh0ny138** [comment]
Mafia III: Definitive Edition

**Comment by BigBoiCJ** [comment]
I'll check later, I currently can't, sorry

**Comment by AnTh0ny138** [comment]
its okay a btw the thing is the dll cannot be found on every game i try to crack i know that i have to use the underground steam forum for the files or something like that but what if the game i am looking for isnt there then what

**Comment by 747DB66FBC** [comment]
Typical antivirus delet

> Finished cracking the game! [ ! ] No Steam API DLL was found in the game! Press enter to exit
> 
> uhh help i don't exactly know how to crack games this is my first so what can i do to make it find the Steam API DLL ?

I had the same problem with anti-virus program false-positive and deleting it. Good luck!

**Comment by BigBoiCJ** [comment]
Might also be that @AnTh0ny138 didn't correctly set-up the games path and/or didn't point to the right game folder

You can check other GitHub issues where I've talked about this :)

I'll try with Mafia III but I'm really lazy right now

**Comment by AnTh0ny138** [comment]
Ok Thanks.
