### ISSUE TITLE
Not fully cracking?

### ISSUE THREAD

**Issue by Kingfrankbob** [BigBoiCJ/SteamAutoCracker#3]
Ive been trying to crack Command and Conquer Red Alert 3 and ive been running the python script, it find the game and folder, but closes as soon as I enter the name of the folder. I also noticed it didnt have ay steam_64api.dll or whatever they are called. I tried moving it out and it just said application error, do I need to put some files in there or something?

**Comment by BigBoiCJ** [comment]
Hi! Thanks for reporting this issue, I'll investigate and try it myself.

If the program closes itself, it means an error occurred.

**Comment by BigBoiCJ** [comment]
Didn't get any crashes, but SAC wasn't able to find the game folder correctly. I'll investigate that.

The game Command & Conquer: Red Alert 3 is not under **Steam API DRM** or **Steam Stub DRM**. I'm not sure what the protection is. You should check the [cs.rin.ru game thread](https://cs.rin.ru/forum/viewtopic.php?f=10&t=75530)

If the crash still occurs and you manage to see the error message before the app closes, please re-open this issue so I can figure out the problem and fix it.

**Comment by BigBoiCJ** [comment]
@Kingfrankbob yep, Steam Auto Cracker is not able to crack this game as it uses "unusual" and unsupported DRMs.

The only supported DRMs are:
- Steam API DRM (steam_api.dll and steam_api64.dll)
- Steam Stub DRM (Steam packed into the .exe of the game)

Most games on Steam uses these DRMs. Bigger companies, like EA or Ubisoft, use their own DRMs.
Some are easy to crack, but aren't supported by this tool.
The best thing to do in this case is check if there is any scene release or check the game thread on forums (such as cs.rin.ru).

This tool is not meant to be able to crack everything, but only the very basic stuff, and make it way faster and easier.

If there are any other easy to bypass DRMs that I could support with this tool, I accept suggestions!

**Comment by Kingfrankbob** [comment]
Thanks, just was checking, nice tool, I did get CnC Remastered to say successfully crack as it has the steamapi.dll and other similar files. I will check the next release out when I get home! I don't really know any other drms, that's why I was stumped. Thanks again and let me know if you need help or need something!

**Comment by tanmingChen305916** [comment]
where should I put the DRM file

**Comment by tanmingChen305916** [comment]
should I put them in the same file with the exe?

**Comment by BigBoiCJ** [comment]
@tanmingChen305916 you shouldn't put any file? Just use the unedited "clean" steam files
