### ISSUE TITLE
unpacking of csgo

### ISSUE THREAD

**Issue by AtroxObitus** [BigBoiCJ/SteamAutoCracker#33]
Hi, can you make a plugin to unpack counter-strike global offensive, too?
It will not work at the moment.

**Comment by BigBoiCJ** [comment]
Outdated now.
Unpack? Not sure what you mean.

CSGO, as well as all Valve/Source games, use some other form of DRM that is still relatively easy to bypass (if you know how to), but isn't supported by SAC. I have no plans on supporting it yet.

You should check Goldberg's emu if you really want to bypass the DRM (although the game is free) :)
You should be able to find NoSteam versions of the game online somewhere
