### ISSUE TITLE
FileNotFoundError: [WinError 3] System cannot find specified path: '1174180/'

### ISSUE THREAD

**Issue by santo161266** [BigBoiCJ/SteamAutoCracker#34]
Traceback (most recent call last):
  File "steam_auto_cracker.py", line 390, in <module>
  File "steam_auto_cracker.py", line 115, in FindGameDirectory
FileNotFoundError: [WinError 3] System cannot find specified path: '1174180/'

**Comment by BigBoiCJ** [comment]
Sorry for the late answer

Please check #13 and #6 or even #22 

This is a pretty common configuration issue I believe. Feel free to send another message if you don't manage to fix the problem.
You can delete your options and re-set them by deleting the `config.ini` file.
