### ISSUE TITLE
ERROR: Unable to load library steamclient64.dll

### ISSUE THREAD

**Issue by CharlieR65** [BigBoiCJ/SteamAutoCracker#36]
Hello!
I would like to understand better and how to resolve this error.
I have the F1 2021 game files and I was able to successfully crack them using the tool.

When I try to start the game, the following error message appears: Unable to load library steamclient64.dll

Prints.:
https://uploaddeimagens.com.br/imagens/6yxRTL8
https://uploaddeimagens.com.br/imagens/Suwdasg

**Comment by BigBoiCJ** [comment]
Hi! Sorry for the late answer.

This game seems to use Denuvo DRM or another type of DRM that SAC can't handle.

It seems like the game wasn't cracked by anyone yet, so it's probably Denuvo, but I could be wrong, I didn't search much.
https://cs.rin.ru/forum/viewtopic.php?f=10&t=112737
