### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by lukrooo** [BigBoiCJ/SteamAutoCracker#37]
![image_2023-11-17_234509212](https://github.com/BigBoiCJ/SteamAutoCracker/assets/151167825/c0882f53-1580-4a88-be69-b7dc72f19e17)
![image_2023-11-17_234527747](https://github.com/BigBoiCJ/SteamAutoCracker/assets/151167825/3961c8ce-d6e2-43de-aef3-fa8b1f86ba40)

**Comment by bylldgo** [comment]
Just install all requirements

**Comment by lukrooo** [comment]
> Just install all requirements

i installed python which is the only requirement and idk what requests is because it doesnt say anywhere

**Comment by BigBoiCJ** [comment]
You need to install the `requests` module, please read the README.md carefully

https://github.com/BigBoiCJ/SteamAutoCracker#requirements

The instructions for installing both required modules `requests` and `pywin32` are detailed on the link I sent ^

Alternatively, if you don't manage to install the modules and run the file by yourself, you can try running the 'compiled' executable file here: https://github.com/BigBoiCJ/SteamAutoCracker/releases

**Comment by ashgithub2100** [comment]
> You need to install the `requests` module, please read the README.md file carefully
> 
> https://github.com/BigBoiCJ/SteamAutoCracker#requirements
> 
> The instructions for installing both required modules `requests` and `pywin32` are detailed on the link I sent ^
> 
> Alternatively, if you don't manage to install the modules and run the file by yourself, you can try running the 'compiled' executable file here: https://github.com/BigBoiCJ/SteamAutoCracker/releases

i am also not able to run the app it just doesnt even start i clicked on it so many times but no responses and i tried downloading everything what should i do?

**Comment by BigBoiCJ** [comment]
> i am also not able to run the app it just doesnt even start i clicked on it so many times but no responses and i tried downloading everything what should i do?

Did you download the right file? You should be downloading [
Steam.Auto.Cracker.v1.2.10.zip](https://github.com/BigBoiCJ/SteamAutoCracker/releases/download/1.2.10/Steam.Auto.Cracker.v1.2.10.zip)

Extract the archive, then run the .exe

If nothing appears, make sure you're running Windows 7+ 64 bits (support is only guaranteed for Windows 10 atm, Windows 10 64 bits is better). Also make sure no antivirus is blocking the .exe or files linked to it (check the threat history).

**Comment by ashgithub2100** [comment]
> > i am also not able to run the app it just doesnt even start i clicked on it so many times but no responses and i tried downloading everything what should i do?
> 
> Did you download the right file? You should be downloading [ Steam.Auto.Cracker.v1.2.10.zip](https://github.com/BigBoiCJ/SteamAutoCracker/releases/download/1.2.10/Steam.Auto.Cracker.v1.2.10.zip)
> 
> Extract the archive, then run the .exe
> 
> If nothing appears, make sure you're running Windows 7+ 64 bits (support is only guaranteed for Windows 10 atm, Windows 10 64 bits is better). Also make sure no antivirus is blocking the .exe or files linked to it (check the threat history).

i have windows 11 64 bits whenever i click on it its doesnt open and nothing works pls help

**Comment by BigBoiCJ** [comment]
@ashgithub2100 seems like you finally managed to open it #38

**Comment by ashgithub2100** [comment]
> @ashgithub2100 seems like you finally managed to open it #38

yea i did thanks for your help but i am getting the line 393 error when cracking?

**Comment by BigBoiCJ** [comment]
> yea i did thanks for your help but i am getting the line 393 error when cracking?

answered in #38 I believe

I'll close this issue now. Please check for the already answered issues if you error is present, else create a new issue (this one was about modules not being installed, please avoid sharing your problems in unrelated issues)
