### ISSUE TITLE
The specified resource type cannot be found in the image file.

### ISSUE THREAD

**Issue by mccalltristan** [BigBoiCJ/SteamAutoCracker#40]
Happens when I try to crack Factorio,

- Couldn't run Steamless on factorio.exe, it is probably not under DRM.

[!!!] A Python error occurred! Writing the error to the error.log file.
---
Traceback (most recent call last):
  File "steam_auto_cracker.py", line 477, in <module>
  File "sac_lib\get_file_version.py", line 4, in GetFileVersion
pywintypes.error: (1813, 'GetFileVersionInfo:GetFileVersionInfoSize', 'The specified resource type cannot be found in the image file.')
---
Error written to error.log, please report it on GitHub or cs.rin.ru
Make sure to blank any personal detail.

Traceback (most recent call last):
  File "steam_auto_cracker.py", line 477, in <module>
  File "sac_lib\get_file_version.py", line 4, in GetFileVersion
pywintypes.error: (1813, 'GetFileVersionInfo:GetFileVersionInfoSize', 'The specified resource type cannot be found in the image file.')

**Comment by BigBoiCJ** [comment]
This often happens when you try to crack a game with an already cracked steam_api(64).dll file.

Did you run the program twice?

**Comment by BigBoiCJ** [comment]
Closed due to inactivity, and issue being invalid
