### ISSUE TITLE
Not working: Couldn't find the folder anywhere

### ISSUE THREAD

**Issue by PrawyCoD1** [BigBoiCJ/SteamAutoCracker#41]
![image](https://github.com/BigBoiCJ/SteamAutoCracker/assets/70172890/115a868e-e97e-474d-9845-19134d2592a9)

**Comment by BigBoiCJ** [comment]
Hi! Sorry for the late answer, sadly you currently can't enter a full folder location, only direct folder names that are in your pirated/steam games location are supported.

Example: if your setup game location is `E:/Games/`, then you should enter `mw`
You can change your setup game location by deleting the `config.ini` file

I guess it's about time that I add this feature #20 

In the meantime, I'm currently working on a GUI version: SAC with a graphical interface, made to be easier to use for most people

**Comment by BigBoiCJ** [comment]
Full/absolute path is now supported in SAC, and SAC GUI is out.
