### ISSUE TITLE
Folder Issue

### ISSUE THREAD

**Issue by ElementalVR** [BigBoiCJ/SteamAutoCracker#42]
I keep writing the correct folder of the game and it says that the folder does not exist on my PC? Please fix this, BigBoiCJ.

**Comment by BigBoiCJ** [comment]
Hi! Sorry that you're experiencing this, but I would need a bit more infos and context to find the problem!

Please check out #41 as it might be related to what you're experiencing

**Comment by BigBoiCJ** [comment]
Closed due to inactivity
