### ISSUE TITLE
Erorr when cracking

### ISSUE THREAD

**Issue by KAZUTO2025** [BigBoiCJ/SteamAutoCracker#49]
Hello just trying to crack the 335300 = Dark souls II scholar of the sin
here is the error_tkinter.log
[error_tkinter.log](https://github.com/BigBoiCJ/SteamAutoCracker/files/14538222/error_tkinter.log)

**Comment by BigBoiCJ** [comment]
Seems like a rare error where the unpacked exe file is still in write. Did you manage to fix the problem?

**Comment by KAZUTO2025** [comment]
well I was using goldberg crack so the achievement watcher will work better in goldberg
after error I simply use ali213 and was successful then I use the goldberg again and that was successful too.

**Comment by KAZUTO2025** [comment]
> Seems like a rare error where the unpacked exe file is still in write. Did you manage to fix the problem?


well I was using goldberg crack so the achievement watcher will work better in goldberg
after error I simply use ali213 and was successful then I use the goldberg again and that was successful too.
