### ISSUE TITLE
Please update ALI213 emu to v8.33.9.23 32/64-bit 

### ISSUE THREAD

**Issue by MrRhinitis** [BigBoiCJ/SteamAutoCracker#50]
Source mafia47 https://cs.rin.ru/forum/viewtopic.php?f=10&t=65887&start=1260

**Comment by BigBoiCJ** [comment]
Thanks, I somehow missed that, I'll get that done

**Comment by BigBoiCJ** [comment]
Updated in SAC GUI v2.0.0
