### ISSUE TITLE
[BUG] - When you fail to enter the AppID, the "Search" button is permanently disabled.

### ISSUE THREAD

**Issue by sergiohzph** [BigBoiCJ/SteamAutoCracker#53]
![image](https://github.com/BigBoiCJ/SteamAutoCracker/assets/138529583/290557cc-bff6-4673-b63b-4fc815aad634)

The only way to fix it is to restart the programme.

PS: And as a suggestion. Disable the maximise button, as it doesn't make sense due to the size of the interface.
`root.resizable(False, False)`

**Comment by BigBoiCJ** [comment]
Indeed, that should be relatively easy to fix

Thanks for the suggestion! I'm pretty new with tkinter

**Comment by BigBoiCJ** [comment]
Will be fixed in the next release coming soon. Already fixed on the main branch by #60

**Comment by BigBoiCJ** [comment]
Thanks for the `root.resizable(False, False)` suggestion. It'll be in the next update :)

**Comment by BigBoiCJ** [comment]
Fixed in v2.0.2 GUI, and suggestion added as well. Thanks for the report!
