### ISSUE TITLE
Please update CreamAPI to v5.1.0.0

### ISSUE THREAD

**Issue by MrRhinitis** [BigBoiCJ/SteamAutoCracker#57]
https://cs.rin.ru/forum/viewtopic.php?f=29&t=70576&hilit=creamapi
If possible, use log build DLL.

**Comment by BigBoiCJ** [comment]
Thanks, will update, but I probably won't use the logging build. Most people don't care, and it's better imo if it doesn't leave any leftovers

**Comment by BigBoiCJ** [comment]
Done! Sorry for the time it took :)
