### ISSUE TITLE
After crack demo game writes "connection error"

### ISSUE THREAD

**Issue by RoskoDaneworth** [BigBoiCJ/SteamAutoCracker#59]
I have downloaded free demo of a Dong Wu game (unity engine) when the demo was available.
It was later removed from access and the demo would not launch writing "no licence" steam error.

Tried SAC latest version. Followed default settings, chose game folder, entered app id, selected ALI213 - game launches but immediately writes "Connection Error. Try again ?(900000)"

Redo with Goldberg emu - same result.
I dont understand what's the issue. Demo doesnt have DRM. Some sort of hard coding in the game ?

**Comment by BigBoiCJ** [comment]
The game might do a web request to a server. By default, both emulators block web requests for privacy and to prevent some DRMs.

To bypass that:
- In ALI213: head to the `SteamConfig.ini` file that was created somewhere inside the game's folder. The GUI should tell you where it was created. Inside, search for `FullBlockNetwork=` and set it to `0` like this: `FullBlockNetwork=0`.
- In Goldberg: create an empty file named `disable_lan_only.txt` and put it inside the `steam_settings` folder that was created in the game. By looking at the GUI, it should tell you where this folder was created.

The web request might also tell the game that the demo is over and not to start. In that case, there's not much you can do as this is a hard coding in the game as you said. I would advise searching on cs.rin.ru to find more information.
The game might also use some other DRMs that SAC doesn't handle, and display this fake error message as a result.

**Comment by RoskoDaneworth** [comment]
Well, neither FullBlockNetwork=0 nor disable_lan_only.txt worked, tested it couple hours after the initial post.

Steamless standalone does not pick any DRM on the .exe, so no luck knowing if it has any.

Tried Darksiders Api, Cold Api with Coldclient, SmartSteamEmu - neither worked, "steam is not initialized" game error.

Tried CODEX steam api build, but could not manage to make it work, game crash with system error. (I'm sure ive made right hex edits as was in github issue post), so might need find help online with it.

So far only seems like hardcoded and needs cracking, which is sad, as demo was free for everyone.

**Comment by BigBoiCJ** [comment]
In those cases I generally go with the experimental goldberg steamclient version with the loader, but I guess that's what Cold Api & Coldclient is. Probably hardcoded if you want my opinion.

Unfortunately I don't have the knowledge to remove this blockage. I don't have a lot of experience with cracking games, despite making SAC.
