### ISSUE TITLE
[WinError 3] The system cannot find the path specified

### ISSUE THREAD

**Issue by rahzadd** [BigBoiCJ/SteamAutoCracker#6]
do you have a discord ?

**Comment by rahzadd** [comment]
![image](https://user-images.githubusercontent.com/111447356/185191775-e81e4d02-018a-4181-ae6d-07f90a81d149.png)

**Comment by rahzadd** [comment]
i get this text

**Comment by BigBoiCJ** [comment]
Hi, sorry for the late answer!

Yes, I do have a discord, but it is a 2nd account I use for anonymity reasons, so I'm not really active on it.

Seems like your config (config.ini) is not set up properly: 

- Please set your game locations through the built-in config feature (by deleting config.ini and starting SAC).
- OR, set it up like this (config.ini):
```
[Locations]
steam = D:/Steam/SteamApps/common/
pirated = D:/Games/Cracks/
```
Use forward slashes `/`, and include a forward slash at the end.
