### ISSUE TITLE
unable to creat interface solution?

### ISSUE THREAD

**Issue by laozhan126** [BigBoiCJ/SteamAutoCracker#66]
unable to creat interface isteamuser

**Comment by BigBoiCJ** [comment]
I'm sorry, I don't get it, please give more details

**Comment by laozhan126** [comment]
> I'm sorry, I don't get it, please give more details

I followed the process and this message popped up when I started the game. I tried two different unlocking methods and it popped up again.![image](https://github.com/BigBoiCJ/SteamAutoCracker/assets/81919632/4da44da5-dd86-4692-9a8b-32fb11baaf70)![image](https://github.com/BigBoiCJ/SteamAutoCracker/assets/81919632/6e204c42-a362-4842-ad0a-95ccbda29187)

**Comment by BigBoiCJ** [comment]
I suspect the game is using a more advanced but still relatively simple DRM. Sadly, SAC doesn't handle this type of cracking (yet). What game is it if I may ask?

You shouldn't launch the game through Steam by the way. Launch the game directly from the .exe

(and you probably shouldn't crack games that are in your Steam folder. Copy or move them elsewhere first to prevent Steam from breaking things)

---

Just checked and "LikeADragon8" seems to be "Like a Dragon: Infinite Wealth", which is under the Denuvo DRM which SAC can't crack.
It seems like this game hasn't been cracked by anyone yet (Denuvo is a pretty good protection): https://cs.rin.ru/forum/viewtopic.php?f=10&t=135475

**Comment by psheep303** [comment]
I have this problem when i play NBA 2K25.How can i fix it?

**Comment by BigBoiCJ** [comment]
> I have this problem when i play NBA 2K25.How can i fix it?

This game is using Denuvo and can't be cracked by SAC. In fact, no one managed to crack it yet: https://cs.rin.ru/forum/viewtopic.php?f=10&t=141996
