### ISSUE TITLE
Drag/Drop game folder onto app window

### ISSUE THREAD

**Issue by Egaliterrier** [BigBoiCJ/SteamAutoCracker#68]
This QOL feature would save a bunch of time, fiddly pressing of buttons and digging through folders or copy/pasting paths.

**Comment by BigBoiCJ** [comment]
Thanks for the suggestion! I was thinking about adding that at some point but forgot to.

I'll check if it's easily doable and if so, I'll add this feature when I have time :)

**Comment by BigBoiCJ** [comment]
Added in v2.2.0 GUI

Thanks to @MasonGuinn for the pull request, your time and code. Your contribution is greatly appreciated!
