### ISSUE TITLE
Received an error when opening an old version of a game

### ISSUE THREAD

**Issue by OmgRod** [BigBoiCJ/SteamAutoCracker#69]
I tried opening the cracked version of Geometry Dash 2.1 and this error popped up when I opened it:
```
INTERFACE=STEAMVIDEO_INTERFACE_V001
CALLER FN=Steam_Client::GetISteamVideo()
APPID=322170
TIME=2024/07/12 - 14:02:10
--------------------

```

**Comment by BigBoiCJ** [comment]
Which steam emu did you try? Try using ALI213 instead, as goldberg might require interface stuff that I didn't add support for

**Comment by OmgRod** [comment]
> Which steam emu did you try? Try using ALI213 instead, as goldberg might require interface stuff that I didn't add support for

I tried the default one. I assume it was goldberg

**Comment by OmgRod** [comment]
Hey! I seemed to be able to get it working but for some reason I had to use Goldberg and ALI213 at the same time for it to work. Thanks for helping though!

**Comment by BigBoiCJ** [comment]
> Hey! I seemed to be able to get it working but for some reason I had to use Goldberg and ALI213 at the same time for it to work. Thanks for helping though!

Weird, glad you got it to work though!
