### ISSUE TITLE
Add more emu like goldberg

### ISSUE THREAD

**Issue by grainne33** [BigBoiCJ/SteamAutoCracker#7]
now we just have one game emu, ali213, do you have a plan to add more emu?

**Comment by BigBoiCJ** [comment]
Closed due to inactivity

**Comment by BigBoiCJ** [comment]
With the GUI version rewrite, I'm thinking about adding goldberg. I currently have a development version with a lot of changes in the way cracks are applied, and it will make it way easier to support other emus

Goldberg's experimental steam_api emu is already supported in my dev version. I'm still polishing it.

**Comment by BigBoiCJ** [comment]
Already added in SAC GUI in [v1.1.0](https://github.com/BigBoiCJ/SteamAutoCracker/releases/tag/1.1.0-gui)

**Comment by BigBoiCJ** [comment]
SAC GUI v2.0.0 stable released
