### ISSUE TITLE
DLC RetrieveAppName requests fail (Steam rate limit)

### ISSUE THREAD

**Issue by NiceGlassesDude** [BigBoiCJ/SteamAutoCracker#8]
I always get this error and I don't have a problem with my internet connection.

**Comment by BigBoiCJ** [comment]
Happens either when Steam is in maintenance or you got rate limited (if the game has a lot of DLCs for example).
It can now happen with Beat Saber when retrieving DLCs. The failed request should be `RetrieveDLC`.

I'll try to increase the retry delay and max attempts in a future release.

I'll also make it so that the `RETRY_DELAY` and `RETRY_MAX` variables are stored in config.ini and are editable.

If you do not believe you got temporarily rate limited, please paste your logs here (and remove any personal information if there's any).

**Comment by NiceGlassesDude** [comment]
> Happens either when Steam is in maintenance or you got rate limited (if the game has a lot of DLCs for example). It can now happen with Beat Saber when retrieving DLCs. The failed request should be `RetrieveDLC`.
> 
> I'll try to increase the retry delay and max attempts in a future release.
> 
> I'll also make it so that the `RETRY_DELAY` and `RETRY_MAX` variables are stored in config.ini and are editable.
> 
> If you do not believe you got temporarily rate limited, please paste your logs here (and remove any personal information if there's any). Also include the AppID/name of the game you were trying to crack.

Thanks for the feedback. Given that it has over 600 DLCs, this makes sense. It worked at times, but it always failed to retrieve specific DLCs at some point.

AppID: 363890 - RPG Maker MV

**Comment by BigBoiCJ** [comment]
Thanks for this useful information.

I've published a new release, v1.2.8, which should fix this problem. This version requires that you delete your config.ini file and generate a new one by launching the .exe and reconfiguring everything OR adding this at the end of your current file:

```
[Advanced]
retrydelay = 15
retrymax = 30
```

I've managed to fully crack the game RPG Maker MV using this new release. It does take significantly more time though, but I don't see an obvious way around that.
Switching your IP with a VPN or a Proxy will help countering the rate limiting and could speed up the process, but now it should try for enough time that you will manage to retrieve all the DLCs with a single connection.

Your feedback is precious. If this fixed (or not) your problem, please notify me :)

**Comment by NiceGlassesDude** [comment]
Thanks for your time and effort, CJ! Everything went smoothly, and I had no problems this time.

**Comment by BigBoiCJ** [comment]
> Thanks for your time and effort, CJ! Everything went smoothly, and I had no problems this time.

Great! I'll close this issue then :)
