### ISSUE TITLE
constant stuttering

### ISSUE THREAD

**Issue by Ketchupppp** [BigBoiCJ/SteamAutoCracker#81]
i have used this tool on many games and it has worked flawlessly but for a recent game it has been nothing but stuttering. i tried cracking it with the goldberg option and its even worse. any idea on what to do?

**Comment by BigBoiCJ** [comment]
Sorry, I don't know. I'm not the author of the cracks, just the tool (SAC) that applies them.

You might want to check on cs.rin.ru for a crack that fixes this problem!
