### ISSUE TITLE
Hi! Help please

### ISSUE THREAD

**Issue by JrSakush** [BigBoiCJ/SteamAutoCracker#83]
Help to crack this game Marvel´s Guardians of the Galaxy App ID: 1088850
What should i do? Master.
[
![Captura de pantalla 2024-10-20 033905](https://github.com/user-attachments/assets/a130ff69-053e-47a9-b034-84e64b98396b)
](url)

**Comment by BigBoiCJ** [comment]
You should include the error logs.

Seems like you have the DODI Repack. Repacks are nearly always cracked versions, so applying SAC on it isn't useful.

**Comment by JrSakush** [comment]
Thanks for the answer!
